name = "amazon1" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "whatsapp.net.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.amazon1.cingoyen.my.id"
custom_domain = true
[[routes]]

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "2afda442-1fcd-4b3e-beec-b25431073d93"
